//
//  MainWorker.swift
//  EAT&FORK
//
//  Created by MacbookAir M1 FoodStory on 12/1/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol MainWorkerprotocol {
    func getMenu(completion: @escaping(_ response: [MenuResponse]) -> Void, failure: @escaping(_ message: String) -> Void)
}

class MainWorker:MainWorkerprotocol
{
    func getMenu(completion:@escaping(_ response:[MenuResponse]) -> Void, failure:@escaping(_ message:String) -> Void) {
        MenuNetworkAPI.getMenu() { (result) in
            switch result {
            case .success(let response):
                completion(response)
            case .failure(let error):
                print(error.localizedDescription)
                failure("Connection fail")
            }
        }
    }
    
}
