//
//  DetailPresenter.swift
//  EAT&FORK
//
//  Created by MacbookAir M1 FoodStory on 12/1/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic
{
  func presentBasketUI(response: Detail.calculateBasketUI.Response)
}

class DetailPresenter: DetailPresentationLogic
{
  weak var viewController: DetailDisplayLogic?
  
  // MARK: Do something
  
    func presentBasketUI(response: Detail.calculateBasketUI.Response)
  {
      let viewModel = Detail.calculateBasketUI.ViewModel(basketPriceLabelText: "฿\(String(format: "%d",                                                                             response.menuSumPrice))",
                                                         basketmenuCountLabelText: String(response.menuSumQuantity))
      
      viewController?.displayBasketUI(viewModel: viewModel)
  }
}
