//
//  DetailModels.swift
//  EAT&FORK
//
//  Created by MacbookAir M1 FoodStory on 12/1/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Detail
{
  // MARK: Use cases
  
  enum calculateBasketUI
  {
    struct Request
    {
        var addMenu: [Main.MainModels.MenuQuantity]
        var menuSumPrice: Int
    }
    struct Response
    {
        var menuSumPrice: Int
        var menuSumQuantity: Int
    }
    struct ViewModel
    {
        var basketPriceLabelText: String
        var basketmenuCountLabelText: String
    }
  }
}
