//
//  DetailModels.swift
//  EAT&FORK
//
//  Created by MacbookAir M1 FoodStory on 12/1/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Detail
{
  // MARK: Use cases
  
  enum calculateBasketUI
  {
    struct Request
    {
        var addMenu: [Main.MainModels.MenuQuantity]
        var menuSumPrice: Int
    }
    struct Response
    {
        var menuSumPrice: Int
        var menuSumQuantity: Int
    }
    struct ViewModel
    {
        var basketPriceLabelText: String
        var basketmenuCountLabelText: String
    }
  }
    
    enum setUpUI
    {
        struct Request
        {
            var menuList: Main.getMenu.ViewModel?
        }
        struct Response
        {
            var menuList: Main.getMenu.ViewModel?
        }
        
        struct ViewModel
        {
            var menuImageURL: String
            var totalPriceLabelText: String
            var menuNameLabelText: String
            var menuDescLabelText: String
            var menuPriceLabelText: String
        }
        
    }
    
    enum addToBasket
    {
        struct Request
        {
            var menuList: Main.getMenu.ViewModel?
            var addMenu: [Main.MainModels.MenuQuantity]
            var wantedQuantity: Int
        }
        struct Response
        {
            var newMenu: Main.MainModels.MenuQuantity
            var wantedQuantity: Int
        }
        
        struct ViewModel
        {
            var newMenu: Main.MainModels.MenuQuantity
            var wantedQuantity: Int
        }
    }
    
    enum increaseButton
    {
        struct Request
        {
           var wantedQuantity: Int
        }
        struct Response
        {
            var wantedQuantity: Int
            var minusButtonIsEnabled: Bool
        }
        
        struct ViewModel
        {
            var minusButtonIsEnabled: Bool
            var wantedQuantity: Int
        }
    }
}
