//
//  DetailInteractor.swift
//  EAT&FORK
//
//  Created by MacbookAir M1 FoodStory on 12/1/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic
{
    func setupBasketUI(request: Detail.calculateBasketUI.Request)
}

protocol DetailDataStore
{

}

class DetailInteractor: DetailBusinessLogic, DetailDataStore
{
  var menu: MenuResponse?
    
  var presenter: DetailPresentationLogic?
  var worker: DetailWorker?
  
  // MARK: Do something
    
    func setupBasketUI(request: Detail.calculateBasketUI.Request){
        var menuSumPrice: Int = 0
        var menuSumQuantity: Int = 0
        
        for items in request.addMenu {

            menuSumPrice += items.menu.price * items.quantity
            menuSumQuantity += items.quantity
        
        }
        
        let response = Detail.calculateBasketUI.Response(menuSumPrice:  menuSumPrice,
                                                         menuSumQuantity: menuSumQuantity)
        presenter?.presentBasketUI(response: response)
    }
    
}
