//
//  MainPresenter.swift
//  EAT&FORK
//
//  Created by MacbookAir M1 FoodStory on 12/1/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic
{
  func presentMenuList(response: Main.getMenu.Response)
  func presentSearchFilterList(response: [MenuResponse])
    
}

class MainPresenter: MainPresentationLogic
{

  weak var viewController: MainDisplayLogic?
    
  // MARK: Do something
  
    func presentMenuList(response: Main.getMenu.Response){
       
        let menuList = response.menuList
        let viewModel = response.menuList?.compactMap({Main.getMenu.ViewModel(id: $0.id, name: $0.name, desc: $0.desc, url: $0.url, price: $0.price, image_url: $0.image_url)}) ?? []
        viewController?.displayMenuList(viewModel: viewModel)
    }
    
    func presentSearchFilterList(response: [MenuResponse]){
       
        let viewModel = response.compactMap({Main.getMenu.ViewModel(id: $0.id, name: $0.name, desc: $0.desc, url: $0.url, price: $0.price, image_url: $0.image_url)})
        viewController?.displayMenuList(viewModel: viewModel)
        
    }

}
