//
//  MainModels.swift
//  EAT&FORK
//
//  Created by MacbookAir M1 FoodStory on 12/1/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main
{
  // MARK: Use cases
    class MainModels {
        class MenuQuantity {
            var menu: Main.getMenu.ViewModel
            var quantity: Int
            init(menu: Main.getMenu.ViewModel, quantity: Int) {
                self.menu = menu
                self.quantity = quantity
            }
        }
    }

  enum getMenu {
    struct Request {
    }
    struct Response{
        var menuList: [MenuResponse]?
        var searchFilterList: [MenuResponse]?
    }
    struct ViewModel{
        var id: Int
        var name: String
        var desc: String
        var url: String
        var price: Int
        var image_url: String
    }
  }
}
