//
//  MainRouter.swift
//  EAT&FORK
//
//  Created by MacbookAir M1 FoodStory on 12/1/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainRoutingLogic
{
    func routeToDetailView(data: Main.getMenu.ViewModel, basketData:[Main.MainModels.MenuQuantity])
    func routeToPaymentView(data: [Main.MainModels.MenuQuantity])
}

protocol MainDataPassing
{
  var dataStore: MainDataStore? { get }
}

class MainRouter: NSObject, MainRoutingLogic, MainDataPassing
{
  weak var viewController: MainViewController?
  var dataStore: MainDataStore?
  
  // MARK: Routing
    
    func routeToDetailView(data: Main.getMenu.ViewModel,basketData: [Main.MainModels.MenuQuantity]){
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "DetailViewController") as! DetailViewController
        destinationVC.menuList = data
        destinationVC.addMenu = basketData
        destinationVC.delegate = self.viewController
        
        self.viewController?.navigationController?.present(destinationVC, animated: true)
      }
    
    func routeToPaymentView(data: [Main.MainModels.MenuQuantity]){
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "PaymentViewController")
        as! PaymentViewController
        destinationVC.delegate = viewController
        destinationVC.addMenu = data.filter({$0.menu.id != 0})
        
        self.viewController?.navigationController?.present(destinationVC,animated: true)
    }
    
  // MARK: Navigation
  
  func navigateToDetail(source: MainViewController, destination: DetailViewController)
  {
    source.show(destination, sender: nil)
  }

  
  // MARK: Passing data
  
//    func passDataToDetail(source: Main.getMenu.ViewModel, destination: inout DetailViewController)
//  {
//      destination.menuList = source as? MenuResponse
//  }
}
