//
//  PaymentPresenter.swift
//  EAT&FORK
//
//  Created by MacbookAir M1 FoodStory on 14/1/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentPresentationLogic
{
    func presentCalculateMenu(response: Payment.calculateMenu.Response)
    func presentCalculateMenuFail(response: Payment.calculateMenu.ResponseFail)
}

class PaymentPresenter: PaymentPresentationLogic
{
    weak var viewController: PaymentDisplayLogic?
    
    // MARK: Do something
    
    func presentCalculateMenu(response: Payment.calculateMenu.Response)
    {
        let viewModel = Payment.calculateMenu.ViewModel(menuSumPriceLabelText: String(format: "฿ %0.2f", response.menuSumPrice),
                                                        servicePriceLabelText: String(format: "฿ %0.2f", response.serviceCost),
                                                        taxPriceLabelText: String(format: "฿ %0.2f", response.taxCost),
                                                        totalPriceLabelText: String(format: "฿ %0.2f", response.totalPrice),
                                                        paidTotalPriceLabelText: String(format: "฿ %0.2f", response.totalPrice))
        viewController?.displayCalculateMenu(viewModel: viewModel)
    }
    
    func presentCalculateMenuFail(response: Payment.calculateMenu.ResponseFail) {
        let viewModel = Payment.calculateMenu.ViewModelFail(addMenu: response.addMenu)
        viewController?.displayCalculateMenuFail(viewModel: viewModel)
    }
}
