//
//  PaymentPresenter.swift
//  EAT&FORK
//
//  Created by MacbookAir M1 FoodStory on 14/1/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentPresentationLogic
{
  func presentSomething(response: Payment.Something.Response)
}

class PaymentPresenter: PaymentPresentationLogic
{
  weak var viewController: PaymentDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Payment.Something.Response)
  {
    let viewModel = Payment.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
